### ISSUE TITLE
PDF.zip genearted by GitHub actions does not caontain all converted markdown files

### ISSUE THREAD

**Issue by cfrome77** [jmunixusers/presentations#69]
The github action ran to create pdf's of the markdown files using marp. The resulting PDF.zip when downloaded did not contain all of the converted versions of the .md files. It only grabbed one that wasn't inside of of a folder (TLS.md). This appears to be an issue with either the `Build PDFs` or the `Zip PDFs` in the workflow .yml file for the action.

**Comment by ripleymj** [comment]
The Action intentionally looks for 'marp: true' at https://github.com/jmunixusers/presentations/blob/2a7307c364a4d29480543e7b8a876207943ea019/.github/workflows/pdf-build.yml#L33 I think any other presentations were left as they were, since the Markdown renders well to HTML.

We could certainly look at taking this further to render all presentations, but a non-marp converter would be needed for other md files.

**Comment by cfrome77** [comment]
We'll then I guess it works as expected, given that all the files matched the grep were included. it just confused me at first that the zip didnt have all the converted files, given the name, but seeing `marp: true` it makes sense.
